# Generated by Django 3.2.25 on 2024-07-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('showMeetups', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(default='New York', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
